### PR TITLE
Another win condition

### PR DESCRIPTION
**Pull request by Numenter**
# Description
Dont know if this is better, but no need for an test_set.

### CODE REVIEW

**Comment by Numenter** [comment]
The function names are horrendous...

**Comment by Numenter** [comment]
your thoughts @ASecondGuy

**Comment by ASecondGuy** [comment]
Looks good. Sorry for letting you wait 4 days. Didn't see it. 
I'll merge it soon probably and fix the names.

**Comment by Numenter** [comment]
Nah , if you want someone to see it, you have to mention them. This one go's on me.

**Pull request merged**
